Iwaid 19 estructura base y enrutamiento
Chris-THC/IWA-Consultorio-Medico pull request #1
Opened 2023-07-21 00:31 UTC by Chris-THC

Create the base UI structure
First create the routes folder, then inside it create the components where the CRUD will be displayed, such as Calendar.jsx, Doctor.jsx, Home.jsx, Medicine.jsx and Patient.jsx.

Then I created a folder conteiner.jsx where 
the menu is rendered and below with the help of the React-router library I made the paths where the user can access, and I added a 404 not found in case the page they are accessing does not exist. 

I also created the menu where I redirect to the corresponding links, using the -Link- component provided by react-router-dom.

2023-07-21 00:47 UTC, SendyCruz commented
Seguir la siguiente estructura en la descripción de tu PR:

### _Ticket_:
- add link to Jira ticket

### _Overview_:
- add basic summary or scope

### _What Changed_:
- add summary of what changed in PR and why

#### _Migrations_:
- add migration name as list

### _How To Test_:
- add details on how to test PR

### _Evidence_:
- add images, logs, or links to show the tests results

2023-07-21 00:48 UTC, SendyCruz commented
Actualizar nombre de PR:
IWAID-19 Estructura base y enrutamiento

2023-07-21 01:01 UTC, SendyCruz requested changes

2023-07-21 01:01 UTC, SendyCruz commented on src/Components/Conteiner.jsx
> +        <h1 className="text-center">404 - Página no encontrada</h1>
Esto parece mas una respuesta de back, Eliminar el 404

2023-07-21 01:01 UTC, SendyCruz commented on src/Components/MenuHamburger.jsx
> +export const MenuHamburger = () => {
MenuHambuerguer -> Menu

2023-07-21 01:01 UTC, SendyCruz commented on src/Components/MenuHamburger.jsx
> +  //% isMenuOpen: A boolean indicating whether the main menu is open or closed.
Remover comentarios

2023-07-21 01:01 UTC, SendyCruz commented on src/Components/MenuHamburger.jsx
> +  const toggleCitas = () => {
Usar inglés en los nombres

2023-07-21 01:01 UTC, SendyCruz commented on src/Components/Routes/Home.jsx
> +      <h1>Home</h1>
Home > Inicio

Lo que queda del lado del código, usar inglés, lo que queda del lado de la vista, es decir lo que ve el usuario sí debe estar en español

2023-07-21 01:01 UTC, SendyCruz commented on src/Components/Routes/Medicine.jsx
> +      <h1>CRUD medicine code here</h1>
En estas secciones agregar un comentario TODO, para indicar que se trabajara en otro ticket, de ser posible indicar en que ticket.

Ej:

// TODO The implementation will be worked on the following ticket IWAID-11

2023-07-21 01:01 UTC, SendyCruz commented on src/Components/Routes/Patient.jsx
> +    <div>
ditto

2023-07-21 01:01 UTC, SendyCruz commented on src/Components/Routes/Doctor.jsx
> +    <div>
ditto

2023-07-21 01:01 UTC, SendyCruz commented on src/Context/AppContext.jsx
> +// Todo: Here I create the context that will be used throughout the web app.
remover comentarios

2023-07-21 01:01 UTC, SendyCruz commented on src/index.js
> +// Import Bootstrap CSS
remover comentarios

2023-07-21 01:03 UTC, SendyCruz requested changes

2023-07-21 01:03 UTC, SendyCruz commented on src/Components/Routes/Calendar.jsx
> +      <h1>CRUD calendar code here</h1>
ditto

2023-07-21 16:58 UTC, SendyCruz requested changes

2023-07-21 16:58 UTC, SendyCruz commented on img/img1.png
esta imagen no es necesaria cargarla al proyecto, solo debe aparecer una captura de esta pantalla en la descripción del PR en la sección de evidencia

2023-07-21 16:58 UTC, SendyCruz commented on src/Components/Menu.jsx
> +          <h3 className="font-weight-bold">iwaid-UI</h3>
Esto podría quedar solo como IWAID

2023-07-28 21:42 UTC, cgarcia-iwa approved these changes

2023-07-28 21:43 UTC, merged