Iwaid 9 crud citas medicas
Chris-THC/IWA-Consultorio-Medico pull request #10
Opened 2023-08-04 17:36 UTC by Mau03gm

Ticket:
[https://iwaids.atlassian.net/browse/IWAID-9?atlOrigin=eyJpIjoiZWQ2M2E0YTU4OTg3NGQ4MzhmZmIxNGNmNjJiZWJmYzMiLCJwIjoiaiJ9]

Overview:
Change the table structure and object search,
create a modal for deletion, update the add and update modals,
and display dummy objects.
Modify the form validations to prevent the entry of erroneous data during the data entry process.

How To Test:

Clone the repository
Install the dependencies
In the project directory, you can run:
npm start
This runs the app in the development mode.
Open http://localhost:3000/ to view it in your browser.

Evidence:

2023-08-07 16:36 UTC, SendyCruz commented
Resolver conflictos

2023-08-07 16:55 UTC, SendyCruz requested changes

2023-08-07 16:55 UTC, SendyCruz commented on src/Components/Date/FormDate.jsx
> +  const options = doctorDataName
```suggestion
  const options = doctorName
```

2023-08-07 16:55 UTC, SendyCruz commented on src/Components/Date/FormDate.jsx
> +  const optionsPatient = patientDataName
```suggestion
  const optionsPatient = patientName
```

2023-08-07 16:55 UTC, SendyCruz commented on src/Components/Date/FormDate.jsx
> +        setTextAlert("No se puede crear una cita antes de la fecha y hora actual");
```suggestion
        setTextAlert("No es posible crear una cita antes de la fecha y hora actual");
```

2023-08-07 16:55 UTC, SendyCruz commented on src/Components/Date/FormDate.jsx
> +        setTextAlert(`Cita con fecha ${data.date} actualizada exitosamente`);
```suggestion
        setTextAlert(`Cita actualizada exitosamente`);
```

2023-08-07 16:55 UTC, SendyCruz commented on src/Components/Date/FormDate.jsx
> +            <option value="">Seleccione una opción</option>
podrías hacerlo de la sig forma:

    <option value="">Seleccione una opción</option>
    {timeOptions.map((option) => (
      <option key={option.value} value={option.value}>
        {option.label}
      </option>
      
      
      const timeOptions = [
  { value: "EIGHT_AM", label: "8:00-8:59 AM" },
  { value: "NINE_AM", label: "9:00-9:59 AM" },
  { value: "TEN_AM", label: "10:00-10:59 AM" },
  { value: "ELEVEN_AM", label: "11:00-11:59 AM" },
  { value: "TWELVE_PM", label: "12:00-12:59 PM" },
  { value: "ONE_PM", label: "1:00-1:59 PM" },
  { value: "TWO_PM", label: "2:00-2:59 PM" },
  { value: "THREE_PM", label: "3:00-3:59 PM" },
  { value: "FOUR_PM", label: "4:00-4:59 PM" },
  { value: "FIVE_PM", label: "5:00-5:59 PM" },
  { value: "SIX_PM", label: "6:00-6:59 PM" },
  { value: "SEVEN_PM", label: "7:00-7:59 PM" },
  { value: "EIGHT_PM", label: "8:00-8:59 PM" },
];

2023-08-07 16:55 UTC, SendyCruz commented on src/Components/Date/table.jsx
> +    //setSearchDate("");
remove

2023-08-07 16:55 UTC, SendyCruz commented on src/Components/Date/table.jsx
> +  //const [searchDate, setSearchDate] = useState("");
remove

2023-08-07 16:55 UTC, SendyCruz commented on src/Components/Date/table.jsx
> +             // setSearchDate("");
remove

2023-08-07 16:55 UTC, SendyCruz commented on src/Components/Date/table.jsx
> +             // setSearchDate("");
remove

2023-08-07 16:55 UTC, SendyCruz commented on src/Components/Date/table.jsx
> +                  <th>Medico</th>
```suggestion
                  <th>Médico</th>
```

2023-08-08 05:33 UTC, SendyCruz requested changes

2023-08-08 05:33 UTC, SendyCruz commented on src/Components/Date/FormDate.jsx
> +  const timeOptions = [
agregar salto de línea

2023-08-08 05:33 UTC, SendyCruz commented on src/Components/Date/table.jsx
> +  const [searchNameDoctor, setSearchNameDoctor] = useState("");
para que tu codigo este ordenado, podrías mover esta dos lineas abajo de la  línea 15

2023-08-08 05:33 UTC, SendyCruz commented on src/Components/Date/table.jsx
> +  const handleShowModalDelete = () => {
handleShowModalDelete  y handleCloseModalDelete, igual por orden moverlos abajo de la línea 37

2023-08-08 05:33 UTC, SendyCruz commented on src/Components/Date/modalDelete.jsx
> +export const MyModalDelete = ({ show, handleClose }) => {
este nombre no debería llevar My

2023-08-08 05:33 UTC, SendyCruz commented on src/Context/DateData.js
> +const dateURL = "http://localhost:8081/iwaid/appointments/";
appointmentURL

2023-08-08 16:39 UTC, SendyCruz requested changes

2023-08-08 16:39 UTC, SendyCruz commented on src/Components/Date/FormDate.jsx
> +  };
agregar salto de línea

2023-08-08 16:39 UTC, SendyCruz commented on src/Components/Date/FormDate.jsx
> +  };
agregar salto de línea

2023-08-08 16:39 UTC, SendyCruz commented on src/Components/Date/FormDate.jsx
> +  } = useContext(GetTheAppContext);
agregar salto de línea

2023-08-08 16:39 UTC, SendyCruz commented on src/Context/DateData.js
> +        console.error("Error al enviar la solicitud:", error);
Dado que este mensaje se repiite en todas las funciones, podría abstraerse

// Manejo de la solicitud

```
const handleRequest = async (url, method, data = null) => {
  try {
    const response = await axios({
      method,
      url,
      data,
    });
    return response.data;
  } catch (error) {
    console.error("Error al enviar la solicitud:", error);
    throw error;
  }
};
```

// uso de la funcion anterior en las demas funciones


```
export const getAllDateDataFunction = async (setAllDataDate) => {
  const response = await handleRequest(APPOINTMENTS_URL, "GET");
  setAllDataDate(response);
};

export const createDateFunction = async (arrayData) => {
  return handleRequest(APPOINTMENTS_URL, "POST", arrayData);
};

export const updateDateFunction = async (arrayData, idDate) => {
  const urlUpdate = `${APPOINTMENTS_URL}${idDate}`;
  return handleRequest(urlUpdate, "PATCH", arrayData);
};

export const deleteDateFunction = async (idDate) => {
  const urlDelete = `${APPOINTMENTS_URL}${idDate}`;
  return handleRequest(urlDelete, "DELETE");
};
```

2023-08-08 16:39 UTC, SendyCruz commented on src/Context/DateData.js
> + const doctorURL = "http://localhost:8081/iwaid/doctors/";
se esta usando?

2023-08-08 16:39 UTC, SendyCruz commented on src/Context/DateData.js
> +const patientURL = "http://localhost:8081/iwaid/patients/";
se esta usando?

2023-08-08 17:58 UTC, Chris-THC commented on src/Context/DateData.js
> +        console.error("Error al enviar la solicitud:", error);
Esta fue la forma que hice para que pudiera funcionar



const handleRequest = async (urlClient, methodClient, dataClient = null) => {
  try {
    const response = await axios({
      method: `${methodClient}`,
      url: `${urlClient}`,
      data: dataClient,
    });
    return response;
  } catch (error) {
    console.error("Error al enviar la solicitud:", error);
    throw error;
  }
};

export const allPrescriptionsFromApiFunction = async (setAllPrescriptionsData) => {
  const response = await handleRequest(prescriptions_URL, "get");
  await setAllPrescriptionsData(response.data);
};

2023-08-08 18:57 UTC, SendyCruz requested changes

2023-08-08 18:57 UTC, SendyCruz commented on src/Components/Date/FloatingAlert.jsx
> +            style={{ backgroundColor: "#d4edda" }}
podrías extraer los estilos a un archivo css, FloatingAlert.css
que este dentro de la misma carpeta

```

.success-alert {
  background-color: #d4edda;
}

.primary-alert {
  background-color: #cce5ff;
}

.danger-alert {
  background-color: #f8d7da;
}

```

en este jsx, agregas el import
import "./FloatingAlert.css"; // Importa el archivo CSS


podrías extraer los alert
```

  const getAlertClass = () => {
    if (actionButtonModal === "Agregar") {
      return "success-alert";
    } else if (actionButtonModal === "Editar") {
      return "primary-alert";
    } else if (actionButtonModal === "Eliminar") {
      return "danger-alert";
    }
  };
```

y ya solo llamarlos de esta forma:



```
  return (
    <Modal show={show} onHide={onClose} centered>
      <Modal.Body className={`text-center ${getAlertClass()}`}>
        <div className="alert text-muted" role="alert">
          {message}
        </div>
      </Modal.Body>
    </Modal>
  );
```
@Chris-THC revisar si te sirve

2023-08-09 16:33 UTC, SendyCruz requested changes

2023-08-09 16:33 UTC, SendyCruz commented on src/Components/Date/FormDate.jsx
> +            <span className="text-danger">*Dato requerido</span>
```suggestion
            <span className="text-danger">Dato requerido</span>
```

2023-08-09 16:33 UTC, SendyCruz commented on src/Components/Date/FormDate.jsx
> +            <span className="text-danger">*Dato requerido</span>
```suggestion
            <span className="text-danger">Dato requerido</span>
```

2023-08-09 18:54 UTC, SendyCruz commented
resolver conflictos

2023-08-09 22:25 UTC, cgarcia-iwa requested changes

2023-08-09 22:25 UTC, cgarcia-iwa commented on src/Components/Date/FormDate.jsx
> +      register("doctorId", { value: (dataGetAllDoctors.find((objeto) => objeto.name === selected[0]).id) });
```suggestion
      register("doctorId", { value: (getAllDoctorsData.find((objeto) => objeto.name === selected[0]).id) });
```

2023-08-09 22:25 UTC, cgarcia-iwa commented on src/Components/Date/FormDate.jsx
> +      else if(responseCreateDate.status === 500){
mover el 500 al archivo de constantes tambien

2023-08-09 22:25 UTC, cgarcia-iwa commented on src/Components/Date/modalDelete.jsx
> +
eliminar espacios sobrantes

2023-08-09 22:25 UTC, cgarcia-iwa commented on src/Context/AppContext.jsx
> +       setDataUserDate,
alinear todos los elemetos

2023-08-09 22:49 UTC, Mau03gm commented on src/Components/Date/FormDate.jsx
> +      register("doctorId", { value: (dataGetAllDoctors.find((objeto) => objeto.name === selected[0]).id) });
es un componente general de la app, no se puede editar

2023-08-09 23:08 UTC, cgarcia-iwa approved these changes

2023-08-10 15:18 UTC, SendyCruz approved these changes

2023-08-10 16:01 UTC, merged