IWAID-27 CRUD Historial Medico
Chris-THC/IWA-Consultorio-Medico pull request #11
Opened 2023-08-08 15:45 UTC by Chris-THC

Ticket:

[IWAID-27 CRUD Historial médico]( https://iwaids.atlassian.net/browse/IWAID-27?atlOrigin=eyJpIjoiZTNhMjEzOTVjNjAyNGYwMDhjZWRhZjUyMmUwNGU0ZmYiLCJwIjoiaiJ9)

Overview:
I created the main structure of the table and also create the modal when you click on edit or add it will behave according to the chosen action. 
Also create a dummy array to test the behavior and rendering of the components.
If you click on the edit button, the data is added to the form ready to be modified.
And the delete button gets the data of the selected patient.
I also added a section that allows you to search by name, doctor or date. 

What Changed:
Use the same structure as in the other CRUDs only with the specific data requested such as medica history. 
I also added a clean button and when the user does not clean and tries to write in another input the others are emptied automatically.
I added the functionality to uncheck if a patient does not have any medical history specifications, pathological or non-pathological.

How To Test:

Clone the repository
Install the dependencies
In the project directory, you can run:
npm start
This runs the app in the development mode.
Open http://localhost:3000/ to view it in your browser.

Evidence:

![Update patient]( https://github.com/Chris-THC/imgTemporal/blob/master/newImg/iwaid-27/prinicipal.png?raw=true)

![Strat Table]( https://github.com/Chris-THC/imgTemporal/blob/master/newImg/iwaid-27/agregar.png?raw=true)

![Update patient]( https://github.com/Chris-THC/imgTemporal/blob/master/newImg/iwaid-27/editar.png?raw=true)

![Add new patient]( https://github.com/Chris-THC/imgTemporal/blob/master/newImg/iwaid-27/eliminar.png?raw=true)

![Add new patient]( https://github.com/Chris-THC/imgTemporal/blob/master/newImg/iwaid-27/Busqueda.png?raw=true)

2023-08-08 17:04 UTC, SendyCruz requested changes

2023-08-08 17:04 UTC, SendyCruz commented on src/Components/MedicalHistory/FormMedicalHistory.jsx
> +      // const createNewPrescription = await createPrescriptionFunction(data);
eliminar comentarios que no sean TODO, si el TODO ya se esta atendiendo entonces borrarlo

2023-08-08 17:04 UTC, SendyCruz commented on src/Components/MedicalHistory/CrudMedicalHistory.jsx
> +      specificFamilyMedicalHistory: "Si tiene un historial medico familair",
```suggestion
      specificFamilyMedicalHistory: "Sí tiene un historial médico familiar",
```

2023-08-08 17:04 UTC, SendyCruz commented on src/Components/MedicalHistory/CrudMedicalHistory.jsx
> +        "Si tiene un historial medico no patologico",
```suggestion
        "Sí tiene un historial médico no patológico",
```

2023-08-08 17:04 UTC, SendyCruz commented on src/Components/Menu.jsx
> +                    Historial Medico
```suggestion
                    Historial Médico
```

2023-08-08 17:04 UTC, SendyCruz commented on src/Components/MedicalHistory/Table.jsx
> +                        Patologicos
```suggestion
                        Patológicos
```

2023-08-08 17:04 UTC, SendyCruz commented on src/Components/MedicalHistory/Table.jsx
> +                        No patologicos
```suggestion
                        No patológicos
```

2023-08-08 17:04 UTC, SendyCruz commented on src/Components/MedicalHistory/Table.jsx
> +                  <th style={{ width: "20%" }}>Antecedentes patologicos</th>
```suggestion
                  <th style={{ width: "20%" }}>Antecedentes patológicos</th>
```

2023-08-08 17:04 UTC, SendyCruz commented on src/Components/MedicalHistory/Table.jsx
> +                  <th style={{ width: "20%" }}>Antecedentes no patologicos</th>
```suggestion
                  <th style={{ width: "20%" }}>Antecedentes no patológicos</th>
```

2023-08-08 19:05 UTC, Chris-THC commented on src/Components/MedicalHistory/FormMedicalHistory.jsx
> +      // const createNewPrescription = await createPrescriptionFunction(data);
Aun no las puedo eliminar ya que me sirven como guía

2023-08-09 16:42 UTC, SendyCruz requested changes

2023-08-09 16:42 UTC, SendyCruz commented on src/Components/MedicalHistory/FormMedicalHistory.jsx
> +    console.log(data);
eliminar log

2023-08-09 16:42 UTC, SendyCruz commented on src/Components/MedicalHistory/FormMedicalHistory.jsx
> +      handleCloseModal();
```suggestion
      closeModal();
```

2023-08-09 16:42 UTC, SendyCruz commented on src/Components/MedicalHistory/FormMedicalHistory.jsx
> +  const deselectFamilyMedicalHistory = () => {
Las funciones deselectFamilyMedicalHistory, deselectPathologicalHistory y deselectNonPathologicalHistory son similares y podrían unificarse en una sola función para reducir la duplicación de código.

```
const deselectHistory = (key) => {
  if (isGetData[key] === true) {
    setIsSelectedFamilyMedicalHistory(true);
  } else if (isGetData[key] === false) {
    setIsSelectedFamilyMedicalHistory(false);
  }
};

useEffect(() => {
  deselectHistory("familyMedicalHistory");
  deselectHistory("pathologicalHistory");
  deselectHistory("nonPathologicalHistory");
}, []);
```

2023-08-09 16:42 UTC, SendyCruz commented on src/Components/MedicalHistory/FormMedicalHistory.jsx
> +  const onSubmitClick = async (data) => {
La validación de datos que se realiza en el onSubmitClick podría mejorarse y hacerse más legible. En lugar de repetir las mismas comprobaciones varias veces, podrías hacerlo de una manera más concisa.

```
const onSubmitClick = async (data) => {
  data.patientsId = patientHistoryId;

  const defaultValue = (value) => (typeof value === "undefined" ? "" : value);

  data.specificFamilyMedicalHistory = defaultValue(
    data.specificFamilyMedicalHistory || dataMedicalHistory.specificFamilyMedicalHistory
  );
  data.specificPathologicalHistory = defaultValue(
    data.specificPathologicalHistory || dataMedicalHistory.specificPathologicalHistory
  );
  data.specificNonPathologicalHistory = defaultValue(
    data.specificNonPathologicalHistory || dataMedicalHistory.specificNonPathologicalHistory
  );

  if (actionButtonModal === "Agregar") {
    handleCloseModal();
  } else if (actionButtonModal === "Editar") {
    handleCloseModal();
  }
};

```

2023-08-09 16:42 UTC, SendyCruz commented on src/Components/MedicalHistory/Table.jsx
> +  const handleShowModalDelete = () => {
```suggestion
  const showModalDelete = () => {
```

2023-08-09 16:42 UTC, SendyCruz commented on src/Components/MedicalHistory/Table.jsx
> +  const handleCloseModalDelete = () => {
```suggestion
  const closeModalDelete = () => {
```

2023-08-09 16:42 UTC, SendyCruz commented on src/Components/MedicalHistory/Table.jsx
> +  const handleClear = () => {
```suggestion
  const clear = () => {
```

2023-08-09 16:42 UTC, SendyCruz commented on src/Components/MedicalHistory/Typeahead/TypeaheadPatient.jsx
> +  const handleInputChange = (input) => {
evitar el handle, revisar en donde mas debe ser removido en este pr

2023-08-09 20:04 UTC, SendyCruz commented
Resolver conflictos

2023-08-09 20:05 UTC, SendyCruz requested changes

2023-08-09 20:05 UTC, SendyCruz commented on src/Components/MedicalHistory/Table.jsx
> +                    // Si no se selecciona ningún filtro, mostrar todos los usuarios
eliminar

2023-08-09 20:14 UTC, cgarcia-iwa requested changes

2023-08-09 20:14 UTC, cgarcia-iwa commented on src/Components/MedicalHistory/FormMedicalHistory.jsx
> +    if (key === true) {
de que tipo es key? si es booleano no es necesario comparar con true / false

2023-08-09 20:14 UTC, cgarcia-iwa commented on src/Components/MedicalHistory/FormMedicalHistory.jsx
> +            <label>¿Tiene antecedentes heredofamiliares?</label>
Barajar la idea de no presentar la informacion como pregunta, solo es necesario entender que representa cada campo

2023-08-09 20:14 UTC, cgarcia-iwa commented on src/Components/MedicalHistory/FormMedicalHistory.jsx
> +            <label>¿Tiene antecedentes no patológicos?</label>
ditto

2023-08-09 20:14 UTC, cgarcia-iwa commented on src/Components/MedicalHistory/FormMedicalHistory.jsx
> +            <label>Especificación de antecedentes no patológicos </label>
dependiendo de la eleccion anterior adaptar las especificaciones

2023-08-09 22:58 UTC, Chris-THC commented on src/Components/MedicalHistory/FormMedicalHistory.jsx
> +    if (key === true) {
key es un prop genérico y toma un valor de acuerdo al objeto que contenga en ese momento

2023-08-09 23:09 UTC, cgarcia-iwa requested changes

2023-08-09 23:09 UTC, cgarcia-iwa commented on src/Components/MedicalHistory/FormMedicalHistory.jsx
> +      console.log(data);
quitar logs

2023-08-09 23:09 UTC, cgarcia-iwa commented on src/Components/MedicalHistory/Typeahead/TypeaheadPatient.jsx
> +    if (Object.keys(dataMedicalHistory).length === 0) {
el if tiene 2 returns iguales, refactorizar para evitar este caso

2023-08-10 15:27 UTC, SendyCruz requested changes

2023-08-10 15:27 UTC, SendyCruz commented on src/Context/History.js
> +export const allHistoryFromApiFunction = async (setAllMedicalHistoryData) => {
```suggestion
export const getAllMedicalHistoryFunction = async (setAllMedicalHistoryData) => {
```

2023-08-10 15:27 UTC, SendyCruz commented on src/Components/MedicalHistory/CrudMedicalHistory.jsx
> +      <Table dataTable={allMedicalHistoryData || []} />
```suggestion
      <Table dataTable={MedicalHistoryData || []} />
```

2023-08-10 15:31 UTC, SendyCruz requested changes

2023-08-10 15:31 UTC, SendyCruz commented on src/Components/MedicalHistory/ModalDelete.jsx
> +              handleShowFloatAlter();
```suggestion
              showFloatAlter();
```

si el nombre de la función cambio entonces tambien debe cambiar el nombre donde sea llamado, buscar los lugares en este pr donde aparece handle en el nombre de funciones y removerlos, recuerden usar la recomendación de iniciar los metodos con un verbo segun lo que realicen

2023-08-10 15:31 UTC, SendyCruz commented on src/Components/MedicalHistory/Typeahead/TypeaheadPatient.jsx
> +        id="pacientes-autocompletado"
usar inglés

2023-08-10 15:32 UTC, Chris-THC commented on src/Context/History.js
> +export const allHistoryFromApiFunction = async (setAllMedicalHistoryData) => {
Tenia este función como getAllMedicalHistoryFunction(), pero me indicaron que lo cambiara a  allHistoryFromApiFunction()

2023-08-10 15:36 UTC, Chris-THC commented on src/Components/MedicalHistory/ModalDelete.jsx
> +              handleShowFloatAlter();
Como es un función genérica handleShowFloatAlter se ocupa en todos los componentes si hago el cambio la aplicación dejara de funcionar , PD aquí aun no se contemplan los cambios indicados ya que este PR se mando a revisión antes de que se iniciara con los cambios que nos indico en la hoja

2023-08-10 16:56 UTC, SendyCruz commented
Resolver conflictos

2023-08-10 16:57 UTC, SendyCruz approved these changes

2023-08-10 18:14 UTC, cgarcia-iwa approved these changes

2023-08-11 01:36 UTC, merged