home, Logo, nav blue and carousel
Chris-THC/IWA-Consultorio-Medico pull request #12
Opened 2023-08-09 06:23 UTC by Mau03gm

Ticket:
[IWAID-30 CRUD Pantalla de inicio](https://iwaids.atlassian.net/browse/IWAID-30?atlOrigin=eyJpIjoiZmQ0MDgxODQ3YjE1NDI0ZWJiNDBlYTE3NjIyODY5ODUiLCJwIjoiaiJ9)

Overview: 
I created the main structure of the home screen and also built a carousel with dummy images of IWA medical office. This carousel automatically switches between images or can be manually swiped, behaving according to the chosen action. I also added a iwa Logo

What Changed: 
I used the same structure for the navigation bar; it only changed its color. I also took into account the comments from the previous reviews.

Evidence: 
<img width="922" alt="inicio1" src="https://github.com/Chris-THC/iwaid-ui/assets/139919533/f638eec8-2375-489e-a6c5-ee910a1d5754">

<img width="913" alt="inicio2" src="https://github.com/Chris-THC/iwaid-ui/assets/139919533/546329a5-b263-41e8-9ac3-cd67221ec83b">
<img width="926" alt="inicioTable" src="https://github.com/Chris-THC/iwaid-ui/assets/139919533/76540688-6ad6-49e9-9079-d13a07464dee">
<img width="200" alt="inicioResponsive" src="https://github.com/Chris-THC/iwaid-ui/assets/139919533/565259b9-d0ab-4708-8408-8e315bcc6183">

2023-08-09 16:15 UTC, SendyCruz commented
¿por qué hay dos logos?
enmi caso prefiero este y considero que es mejor solo mantener uno
![image](https://github.com/Chris-THC/iwaid-ui/assets/129317505/ec92a8f5-5aea-4fc3-a7bd-84b09e370a9b)

Solo a cambia a Mayus la M

2023-08-09 16:17 UTC, SendyCruz requested changes

2023-08-09 16:17 UTC, SendyCruz commented on src/Components/Initation/Initation.jsx
> +    dots: true, // Mostrar los puntos de navegación
borrar los comentarios

2023-08-09 16:17 UTC, SendyCruz commented on src/Css/imagesCss.css
> +    /* Ajusta los estilos según tus necesidades para pantallas más pequeñas */
eliminar comentarios

2023-08-09 16:17 UTC, SendyCruz commented on src/Css/imagesCss.css
> +  background-color: #39a0ff/* Tu color azul personalizado */
ditto

2023-08-09 16:17 UTC, SendyCruz commented on src/Css/imagesCss.css
> +  background-color: #39a0ff/* Tu color azul personalizado */
ditto

2023-08-09 16:17 UTC, SendyCruz commented on src/Css/imagesCss.css
> +  box-shadow: 0px 20px 20px rgba(0, 0, 0, 0.1); /* Sombra inferior */
ditto

2023-08-09 16:18 UTC, SendyCruz commented
¿podría cambiarse el azul, por un tono menos intenso? para que no sea tan agresivo a la vista?

2023-08-09 16:30 UTC, SendyCruz commented
Al revisar en local, el logo no se aprecia bien, parece no tener el tamaño adecuado, por lo que no es agradable a la vista
![image](https://github.com/Chris-THC/iwaid-ui/assets/129317505/56d4e0ca-625e-48f0-b704-318f680e46e9)


Encuentro tambien, mucho espacio despediciado en la parte de abajo, por lo que solo veo diferentes el color de la barra y el carrusel, aun no parece tener una optimización completa .

Podrían agregarse tal vez un pie de página para aprovechar ese espacio

ejemplo esta es la pagina de inicio de covadonga
![image](https://github.com/Chris-THC/iwaid-ui/assets/129317505/23009cec-d868-41bd-8e41-43e60b0d101f)
el carrusel abarca practicamente toda la pantalla y ademas al final de la pagina hay información de contacto y dirección 
![image](https://github.com/Chris-THC/iwaid-ui/assets/129317505/4bd2065a-c536-4d29-9f55-5c00864dc134)

2023-08-09 17:06 UTC, cgarcia-iwa requested changes
Las imagenes de fondo azul se pierden mucho, sobre todo la primera que lleva 2 tipos de azul, analizar la idea de sustituirla o en su defecto cambiar el color de fondo

2023-08-09 17:06 UTC, cgarcia-iwa commented on src/Components/Initation/Initation.jsx
> +
borrar espacios vacios

2023-08-09 17:06 UTC, cgarcia-iwa commented on src/Components/Initation/Initation.jsx
> +          <img className="imgI" src={consultorio} alt="" />
que indica el alt y por que todos estan vacios?

2023-08-09 17:06 UTC, cgarcia-iwa commented on src/Components/Menu.jsx
> +                  id="Dropdown"
alinear todos los elementos

2023-08-09 17:06 UTC, cgarcia-iwa commented on src/Css/imagesCss.css
> +.imgI{
utilizar nombres mas enfaticos en lo que representan

2023-08-11 01:26 UTC, SendyCruz commented
esta sección de los menus sugiero que se mantenga donde estaban ya que si se abre una y despues la otra y sino se cerro la primera, abarca mucho espacio en la pantalla y sus monitores son pequeños, al mostrarlo se vera muy enorme 
![image](https://github.com/Chris-THC/iwaid-ui/assets/129317505/40613a06-64c3-495d-8501-7e1e8a0f8cf3)


Mantener las opciones consecutivas como anteriormente se tenia, solo cambiar la ubicación

2023-08-11 01:31 UTC, SendyCruz requested changes

2023-08-11 01:31 UTC, SendyCruz commented on src/Components/Initation/Initation.jsx
> +      <h5 class="card-title text-light">Valores que nos Definen</h5>
```suggestion
      <h5 class="card-title text-light">Valores que nos definen</h5>
```

2023-08-11 01:31 UTC, SendyCruz commented on src/Components/Initation/Initation.jsx
> +      <p class="card-text text-light">Consulta Médica Integral: Un enfoque holístico para abordar tus necesidades médicas en su totalidad.
Consulta Médica Integral:
Chequeos Preventivos:
Cuidado de Enfermedades Crónicas: 
Vacunación y Prevención: 
Atención en Urgencias Menores:
Asesoría Nutricional: 


Colocar en negritas

2023-08-11 01:31 UTC, SendyCruz commented on src/Components/Initation/Initation.jsx
> +Teléfono: (123) 456-7890</p>
Darle un salto de línea a cada dato:

IWA Consultorio Médico 
Dirección: Calle Ficticia #123, Colonia Imaginaria, Orizaba, Veracruz, México. 
Teléfono: (123) 456-7890


Dirección y telefono en negritas

2023-08-11 01:31 UTC, SendyCruz commented on src/Components/Images/IWALogo (2).jpg
dejar solo el logo que se va a usar, los que no, removerlos

2023-08-11 03:58 UTC, SendyCruz approved these changes

2023-08-11 03:58 UTC, SendyCruz commented on src/Components/Images/IWALogo.jpg
cambiar el nombre de los archivos a: iwa_logo

2023-08-11 03:58 UTC, SendyCruz commented on src/Components/Images/IWALogoFooter.jpg
iwa_logo_footer

2023-08-11 03:58 UTC, SendyCruz commented on src/Components/Images/c.jpg
cambiar el nombre por algo mas descriptivo en inglés

2023-08-11 03:58 UTC, SendyCruz commented on src/Components/Images/consultorio-exterior.jpg
usar inglés

2023-08-11 03:58 UTC, SendyCruz commented on src/Components/Images/consultorioimg.jpg
usar un nombre mas significativo e inglés

2023-08-11 03:58 UTC, SendyCruz commented on src/Components/Images/doctor2.jpg
ditto

2023-08-11 03:58 UTC, SendyCruz commented on src/Components/Initation/Initation.jsx
> +export function IMG(){
cambiar nombre, usar noenclatura adecuada: showLogoImage

2023-08-11 03:58 UTC, SendyCruz commented on src/Components/Initation/Initation.jsx
> +export const CarouselComponent = () => {
```suggestion
export const showCarouselComponent = () => {
```

2023-08-11 03:58 UTC, SendyCruz commented on src/Components/Initation/Initation.jsx
> +export const Footer =()=>{
```suggestion
export const showFooter =()=>{
```

2023-08-11 17:24 UTC, merged