http status Generic
Chris-THC/IWA-Consultorio-Medico pull request #16
Opened 2023-08-10 06:28 UTC by Mau03gm

Ticket:
Overview:
What changed:
Evidence:
<img width="893" alt="addStatus" src="https://github.com/Chris-THC/iwaid-ui/assets/139919533/d34c2c67-9353-4cd4-a20e-393567adaeb3">
<img width="860" alt="updateStatus" src="https://github.com/Chris-THC/iwaid-ui/assets/139919533/c8c98fe6-038d-4c24-965b-ae0af35fdcde">
<img width="875" alt="deleteStatus" src="https://github.com/Chris-THC/iwaid-ui/assets/139919533/cccee4fc-bb94-476a-80e4-06a1d63268ad">

2023-08-10 16:42 UTC, SendyCruz requested changes

2023-08-10 16:42 UTC, SendyCruz commented on src/Components/Patient/MyModalDelete.jsx
> +            if (response.status === statusDeleted) {
eliminar cambio de este archivo, ya que sera borrado en IWAID-34

2023-08-10 16:42 UTC, SendyCruz commented on src/Components/HTTP/HTTPStatus.js
Nombre de la carpeta HttpStatus
Nombre del archivo HttpStatusCode

2023-08-10 16:46 UTC, SendyCruz requested changes

2023-08-10 16:46 UTC, SendyCruz commented on src/Components/HTTP/HTTPStatus.js
Unificar statusUpdated y statusDeleted, solo dejar statusOk, actualizar donde sea necesario
![image](https://github.com/Chris-THC/iwaid-ui/assets/129317505/f7b1533c-2011-4954-a8cd-bf4c6cbcfcbf)

2023-08-10 19:32 UTC, SendyCruz requested changes

2023-08-10 19:32 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/ModalDelete.jsx
>  import { useContext } from "react";
los cambios en los ModalDelete, removerlos

2023-08-10 19:32 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/ModalDelete.jsx
>  import { useContext } from "react";
los cambios en los ModalDelete, removerlos, ya que estos archivos se van a borrar

2023-08-10 19:37 UTC, cgarcia-iwa requested changes

2023-08-10 19:37 UTC, cgarcia-iwa commented on src/Components/MedicalPrescriptions/ModalDelete.jsx
> +            if (response.status === 200) {
no existe alguna constante que se pueda usar en vez del 200?

2023-08-10 19:49 UTC, Mau03gm commented on src/Components/MedicalPrescriptions/ModalDelete.jsx
> +            if (response.status === 200) {
sendy me dijo que que debo remover cambios del modalDelete, por eso no tiene

2023-08-10 21:14 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/ModalDelete.jsx
> +            if (response.status === 200) {
@cgarcia-iwa estos archivos se van a ir porque hay un pr con la modificación del modal generico

2023-08-11 01:13 UTC, SendyCruz approved these changes

2023-08-11 01:20 UTC, merged