IWAID-10 CRUD Pacientes
Chris-THC/IWA-Consultorio-Medico pull request #3
Opened 2023-07-22 05:00 UTC by Chris-THC

Ticket:
https://iwaids.atlassian.net/browse/IWAID-10?atlOrigin=eyJpIjoiZmVhNTc0ZGY2MmNjNGYwZTg4N2E1M2ZiZTA0NmI2NzAiLCJwIjoiaiJ9

Overview:
Create the main structure of the table and also create the modal when clicking on edit or add this will behave according to the action chosen. 
Also, create a dummy array to test the behavior and rendering of the components.
If you click on the edit button, the data is added to the form ready to be modified.
And the delete button obtains the data of the selected patient.

What Changed:
IJust add a folder to the original structure, and just add a tag in the patient.jsx file.

How To Test:

Clone the repository
Install the dependencies
In the project directory, you can run:
npm start
This runs the app in the development mode.
Open http://localhost:3000/ to view it in your browser.

Evidence:

![Strat Table](https://github.com/Chris-THC/imgTemporal/blob/master/crud-pacientes/inicio.png?raw=true)

![Add new patient](https://github.com/Chris-THC/imgTemporal/blob/master/crud-pacientes/agregar.png?raw=true)

![Update patient](https://github.com/Chris-THC/imgTemporal/blob/master/crud-pacientes/editar.png?raw=true)

2023-07-22 20:33 UTC, SendyCruz commented
Tu rama debe apuntar a la rama donde tienes la estructura inicial y ocupar los archivos que ya definiste

2023-07-22 20:39 UTC, SendyCruz requested changes

2023-07-22 20:39 UTC, SendyCruz commented on src/Components/Patient/FormPatient.jsx
> +              <input
Agregar una validación que confirme que la fecha que se está ingresando no es una fecha futura

2023-07-22 20:39 UTC, SendyCruz commented on src/Components/Patient/FormPatient.jsx
> +            <input
Validar que el campo no acepte numeros

2023-07-22 20:39 UTC, SendyCruz commented on src/Components/Patient/TablePatient.jsx
> +                  <th>Opcion</th>
Opción

2023-07-22 20:39 UTC, SendyCruz commented on src/Components/Routes/Prescriptions.jsx
> +      <h1>Prescripciones médicas</h1>
Usar singular, me parece que estos cambios pertenecen a otro pr

2023-07-22 20:39 UTC, SendyCruz commented on src/Context/AppContext.jsx
> +  const [dataTest, setDataTest] = useState([
Agregar un TODO que indique que estos datos duros se van eliminar al hacer la conexión con el back

2023-07-24 18:59 UTC, Chris-THC commented
I have addressed all the comments and added the search by name

2023-07-25 17:21 UTC, SendyCruz commented
En la sección de filtros esperaria ver los campos inputs disponibles para el filtrado, algo como lo siguiente, tambien agregar un boton para limpiar los filtros
![image](https://github.com/Chris-THC/iwaid-ui/assets/129317505/5e4a9980-e9fd-42dc-ac54-5b73d87872a3)

2023-07-25 17:24 UTC, SendyCruz commented
esta rama debe apuntar a IWAID-19

2023-07-25 17:31 UTC, SendyCruz requested changes

2023-07-25 17:31 UTC, SendyCruz commented on src/Components/Conteiner.jsx
> +          Lo sentimos, la página que estás buscando no se encuentra.
```suggestion
          Lo sentimos, la página que estás buscando no se encuentra disponible.
```

2023-07-25 17:31 UTC, SendyCruz commented on src/Components/Patient/FormPatient.jsx
> +              {errors.fechaNacimineto && (
fechaNacimiento

2023-07-25 17:31 UTC, SendyCruz commented on src/Components/Patient/FormPatient.jsx
> +        <div>
El botón debe habilitarse solo si los campos de los datos son correctos

2023-07-25 17:31 UTC, SendyCruz commented on src/Components/Patient/TablePatient.jsx
> +                        <MdChangeCircle className="btn-icon-lg" /> Editar
El botón debe habilitarse solo si los campos de los datos son correctos

2023-07-25 17:33 UTC, SendyCruz commented
Considerar los comentarios para otros CRUDS

2023-07-25 21:59 UTC, Chris-THC commented on src/Components/Patient/TablePatient.jsx
> +                        <MdChangeCircle className="btn-icon-lg" /> Editar
Al reutilizar el mismo formulario una vez solucionado el comentario de arriba que era el de agregar, se soluciona el de editar, por ende, el botón se activa siempre y cuando los datos sean válidos.

2023-07-25 22:02 UTC, Chris-THC commented
I have addressed all the comments and I edited the search by name, phone and email. As in the example you showed me  :)

Evidence:

![Strat Table](https://github.com/Chris-THC/imgTemporal/blob/master/crud-pacientes/limpiar.png?raw=true)

2023-07-27 18:54 UTC, Chris-THC commented
Here is the evidence of the validation of the form fields 

Evidence: [iwaid-10](https://drive.google.com/file/d/1S33s7JFncCp8BbTevBpml3uqlVyVkP9S/view)

2023-07-31 04:50 UTC, SendyCruz commented
Tendría que apuntar a la 19

2023-07-31 04:56 UTC, Chris-THC commented
Disculpa creí que ya se había hecho el cambio :(

2023-07-31 05:00 UTC, SendyCruz requested changes

2023-07-31 05:00 UTC, SendyCruz commented on src/Components/Patient/FormPatient.jsx
> +          <label>* RFC</label>
El asterisco debe ir del lado derecho y debe ser en color rojo, revisar si se puede ocupar otra etiqueta

2023-07-31 05:00 UTC, SendyCruz commented on src/Components/Patient/MyModalDelete.jsx
> +        <Modal.Title>Confirmar Eliminación</Modal.Title>
Confirmar eliminación

2023-07-31 05:00 UTC, SendyCruz commented on src/Components/Patient/MyModalDelete.jsx
> +        <p>¿Estás seguro de que deseas eliminar este Paciente?</p>
paciente

2023-07-31 05:00 UTC, SendyCruz commented on src/Components/Patient/TablePatient.jsx
> +                      <label>Rango año de nacimiento</label>
Por que la fecha de nacimiento sería un rango?

2023-07-31 05:00 UTC, SendyCruz commented on src/Components/Patient/TablePatient.jsx
> +                  <th>Genero</th>
Género

2023-07-31 05:00 UTC, SendyCruz commented on src/Components/Patient/TablePatient.jsx
> +                  <th>Acción</th>
Acciones

2023-07-31 05:00 UTC, SendyCruz commented on src/Components/Patient/TablePatient.jsx
> +                          // setTextAlert(`Se ha eliminado: ${item.nombre}`);
Borrar comentarios

2023-07-31 05:21 UTC, Chris-THC commented on src/Components/Patient/TablePatient.jsx
> +                      <label>Rango año de nacimiento</label>
Por que el ticket solicita un filtro mediante un rango de fecha de nacimiento : https://iwaids.atlassian.net/browse/IWAID-10?atlOrigin=eyJpIjoiMWZjYTQyNzk3NDllNGUwZmFiZmU5ZmU4NjFhMDRmZTYiLCJwIjoiaiJ9

Mostré esa función al equipo de backend y mencionaron que estaba era una buena opción :)

2023-08-01 00:23 UTC, SendyCruz requested changes

2023-08-01 00:23 UTC, SendyCruz commented on src/Components/Patient/FormPatient.jsx
> +    setRfcValue(inputValue); // Actualiza el estado rfcValue con el valor en mayúsculas
remover comentarios

2023-08-01 00:23 UTC, SendyCruz commented on src/Components/Patient/FormPatient.jsx
> +      setRfcError("El RFC debe tener un formato válido en mayúsculas.");
```suggestion
      setRfcError("El RFC debe tener un formato válido.");
```

2023-08-01 00:23 UTC, SendyCruz commented on src/Components/Patient/FormPatient.jsx
> +                El campo es solicitado o el campo del nombre no debe de llevar
Dato requerido o ...

2023-08-01 00:23 UTC, SendyCruz commented on src/Components/Patient/FormPatient.jsx
> +                  El dato es solicitado o la fecha no puede ser mayor a la fecha
Dato requerido ....

2023-08-01 00:23 UTC, SendyCruz commented on src/Components/Patient/FormPatient.jsx
> +              <span className="text-danger">El dato es requerido</span>
```suggestion
              <span className="text-danger">Dato requerido</span>
```

2023-08-01 00:23 UTC, SendyCruz commented on src/Components/Patient/FormPatient.jsx
> +                El dato es requerido y no se aceptan números{" "}
Dato requerido ...

2023-08-01 00:23 UTC, SendyCruz commented on src/Components/Patient/MyModalDelete.jsx
> +        <p>¿Estás seguro de que deseas eliminar este paciente?</p>
```suggestion
        <p>¿Está seguro de que desea eliminar este paciente?</p>
```

2023-08-01 19:31 UTC, cgarcia-iwa requested changes

2023-08-01 19:31 UTC, cgarcia-iwa commented on src/Components/Patient/CrudPatient.jsx
> +      <TablePatient dataTable={getDataAllPatients || []} />
es posible hacer este cambio?
```suggestion
      <TablePatient dataTable={getAllPatientsData || []} />
```

2023-08-01 19:31 UTC, cgarcia-iwa commented on src/Components/Patient/FormPatient.jsx
> +        await getAllPatientDataFunction(setGetDataAllPatients);
que indica el setGetData aqui? renombrar a algo que sea mas coherente

2023-08-01 19:31 UTC, cgarcia-iwa commented on src/Context/AppContext.jsx
> +  // setGetDataAllPatients([
si ya no se usa para nada este contenido borrarlo, respaldalo en otro archivo fuera del repositorio si lo necesitas

2023-08-01 19:31 UTC, cgarcia-iwa commented on src/Context/PatientData.js
> +    console.log(urlUpdate);
borrar todos los console.log

2023-08-01 23:04 UTC, SendyCruz commented
en esta sección, esperaría que todos los elementos de filtrado esten en una misma linea o nivel  incluyendo el boton de limpiar filtros
![image](https://github.com/Chris-THC/iwaid-ui/assets/129317505/0ff2da98-c84e-47a9-ad04-4262853c9fa2)

2023-08-01 23:11 UTC, SendyCruz requested changes

2023-08-01 23:11 UTC, SendyCruz commented on src/Components/Patient/FormPatient.jsx
> +        setTextAlert("Error al agregar al paciente");
```suggestion
        setTextAlert("Error al actualizar al paciente");
```

2023-08-01 23:11 UTC, SendyCruz commented on src/Components/Patient/FormPatient.jsx
> +                Dato requerido o el campo del nombre no debe de llevar números
```suggestion
                Dato requerido o solo acepta letras
```

2023-08-01 23:11 UTC, SendyCruz commented on src/Components/Patient/FormPatient.jsx
> +                <span className="text-danger">El dato es requerido</span>
```suggestion
                <span className="text-danger">Dato es requerido</span>
```

2023-08-01 23:11 UTC, SendyCruz commented on src/Components/Patient/FormPatient.jsx
> +                El número de teléfono es requerido
```suggestion
                Dato requerido
```

2023-08-01 23:11 UTC, SendyCruz commented on src/Components/Patient/MyModalDelete.jsx
> +              setTextAlert(`Se eliminó al médico ${dataUserPatient.name}`);
```suggestion
              setTextAlert(`Se eliminó al paciente ${dataUserPatient.name}`);
```

2023-08-01 23:11 UTC, SendyCruz commented on src/Components/Patient/MyModalDelete.jsx
> +              setTextAlert("Error al eliminar el médico");
```suggestion
              setTextAlert("Error al eliminar el paciente");
```

2023-08-01 23:11 UTC, SendyCruz commented on src/Components/Patient/TablePatient.jsx
> +                        placeholder="Buscar por año de nacimiento..."
```suggestion
                        placeholder="Buscar por fecha de nacimiento..."
```

2023-08-01 23:11 UTC, SendyCruz commented on src/Components/Routes/Patient.jsx
>    // TODO: The implementation will be worked on the following ticket IWAID-10
remover

2023-08-02 15:52 UTC, SendyCruz commented
Actualizar rama con develop

2023-08-02 15:53 UTC, SendyCruz commented
Agregar evidencia de los ajustes solicitados del filtrado

2023-08-02 16:00 UTC, SendyCruz requested changes

2023-08-02 16:00 UTC, SendyCruz commented on src/Components/Patient/FormPatient.jsx
> +                <span className="text-danger">Dato es requerido</span>
```suggestion
                <span className="text-danger">Dato requerido</span>
```

2023-08-02 16:00 UTC, SendyCruz commented on src/Components/Patient/FormPatient.jsx
> +              <span className="text-danger">Debe tener 10 dígitos</span>
```suggestion
              <span className="text-danger">Máximo 10 dígitos</span>
```

2023-08-02 16:00 UTC, SendyCruz commented on src/Components/Patient/FormPatient.jsx
> +              placeholder="Agregar su email"
```suggestion
              placeholder="example@ex.com"
```

2023-08-02 16:00 UTC, SendyCruz commented on src/Context/PatientData.js
> +const doctorURL = "http://localhost:8081/iwaid/patients/";
```suggestion
const patientURL = "http://localhost:8081/iwaid/patients/";
```

2023-08-02 16:00 UTC, SendyCruz commented on src/Context/PatientData.js
> +    const response = await axios.get(doctorURL);
```suggestion
    const response = await axios.get(patientURL);
```

2023-08-02 16:00 UTC, SendyCruz commented on src/Context/PatientData.js
> +  const urlUpdate = `${doctorURL}${idDoctor}`;
```suggestion
  const urlUpdate = `${patientURL}${idPatient}`;
```

2023-08-02 16:00 UTC, SendyCruz commented on src/Context/PatientData.js
> +export const deletePatientFunction = async (idDoctor) => {
```suggestion
export const deletePatientFunction = async (idPatient) => {
```

2023-08-02 16:00 UTC, SendyCruz commented on src/Context/PatientData.js
> +    const urlDelete = `${doctorURL}${idDoctor}`;
```suggestion
    const urlDelete = `${patientURL}${idPatient}`;
```

2023-08-02 16:00 UTC, SendyCruz commented on src/Context/PatientData.js
> +    const response = await axios.post(doctorURL, arrayData);
```suggestion
    const response = await axios.post(patientURL, arrayData);
```

2023-08-02 16:00 UTC, SendyCruz commented on src/Context/PatientData.js
> +export const updatePatientFunction = async (arrayData, idDoctor) => {
```suggestion
export const updatePatientFunction = async (arrayData, idPatient) => {
```

2023-08-02 18:57 UTC, SendyCruz approved these changes

2023-08-02 19:00 UTC, cgarcia-iwa approved these changes

2023-08-02 19:00 UTC, cgarcia-iwa commented on src/Components/Patient/FormPatient.jsx
> +                Dato requerido o solo acepta letras
considerar en el futuro separar los errores como en otro crud

2023-08-02 19:07 UTC, merged