IWAID-12 CRUD  Prescripciones Medicas
Chris-THC/IWA-Consultorio-Medico pull request #5
Opened 2023-07-24 23:35 UTC by Chris-THC

Ticket:

[IWAID-12 CRUD Prescripciones médicas](https://iwaids.atlassian.net/browse/IWAID-12?atlOrigin=eyJpIjoiN2I0NmJiMTIyOTk3NDFkOTg4NTNlMDE4YjkzMzAxNGYiLCJwIjoiaiJ9)

Overview:
I created the main structure of the table and also create the modal when you click on edit or add it will behave according to the chosen action. 
Also create a dummy array to test the behavior and rendering of the components.
If you click on the edit button, the data is added to the form ready to be modified.
And the delete button gets the data of the selected patient.
I also added a section that allows you to search by name, doctor or date. 

What Changed:
Use the same structure as in the other CRUDs only with the specific data requested such as medical preinscription. 
I also took into account the comments of the previous PRs, so the add and edit buttons are only activated when the data is valid in the form.
By the way the search is now by name, doctor and date, I also validated that the date is not later than the current one.  
I also added a clean button and when the user does not clean and tries to write in another input the others are emptied automatically.  

How To Test:

Clone the repository
Install the dependencies
In the project directory, you can run:
npm start
This runs the app in the development mode.
Open http://localhost:3000/ to view it in your browser.

Evidence:

![Update patient](https://github.com/Chris-THC/imgTemporal/blob/master/newImg/iwaid-12/pricipal.png?raw=true)

![Strat Table](https://github.com/Chris-THC/imgTemporal/blob/master/newImg/iwaid-12/agregar.png?raw=true)

![Update patient](https://github.com/Chris-THC/imgTemporal/blob/master/newImg/iwaid-12/added.png?raw=true)

![Add new patient](https://github.com/Chris-THC/imgTemporal/blob/master/newImg/iwaid-12/toDeleted.png?raw=true)

![Add new patient](https://github.com/Chris-THC/imgTemporal/blob/master/newImg/iwaid-12/deleted.png?raw=true)

2023-08-02 19:10 UTC, cgarcia-iwa requested changes

2023-08-02 19:10 UTC, cgarcia-iwa commented on src/Components/MedicalPrescriptions/TableMedicalPrescriptions.jsx
> +                  <th>Nombre</th>
```suggestion
                  <th>Paciente</th>
```

2023-08-02 19:10 UTC, cgarcia-iwa commented on src/Components/MedicalPrescriptions/TableMedicalPrescriptions.jsx
> +                          console.log(item.nombre);
borrar logs

2023-08-02 19:10 UTC, cgarcia-iwa commented on src/Css/TablaMedicalPrescriptions.css
> +
define si el nombre del archivo estara en ingles o español

2023-08-04 16:21 UTC, SendyCruz requested changes

2023-08-04 16:21 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/FormMedicalPrescriptions.jsx
> +                <span className="text-danger">El dato es requerido</span>
```suggestion
                <span className="text-danger">Dato requerido</span>
```

2023-08-04 16:21 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/FormMedicalPrescriptions.jsx
> +              <label>Medico</label>
```suggestion
              <label>Médico</label>
```

2023-08-04 16:21 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/FormMedicalPrescriptions.jsx
> +                <span className="text-danger">El dato es requerido</span>
```suggestion
                <span className="text-danger">Dato requerido</span>
```

2023-08-04 16:21 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/FormMedicalPrescriptions.jsx
> +                El dato es requerido o la fecha no puede ser posterior a la
```suggestion
                Dato requerido o la fecha no puede ser posterior a la
```

2023-08-04 16:21 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/FormMedicalPrescriptions.jsx
> +              <span className="text-danger">El dato es requerido</span>
```suggestion
              <span className="text-danger">Dato requerido</span>
```

2023-08-04 16:21 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/PrescriptionTypeahead/TypeaheadDoctor.jsx
> +  //   const { setPrescriptionPatientId } = useContext(GetTheAppContext);
remover

2023-08-04 16:21 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/PrescriptionTypeahead/TypeaheadDoctor.jsx
> +      {/* {selectedPatient.length > 0 &&
remover comentario

2023-08-04 16:21 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/PrescriptionTypeahead/TypeaheadMedicine.jsx
> +  //   const { setPrescriptionPatientId } = useContext(GetTheAppContext);
remover comentarios

2023-08-04 16:21 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/PrescriptionTypeahead/TypeaheadMedicine.jsx
> +      {/* {selectedPatient.length > 0 &&
remover comentarios

2023-08-04 16:21 UTC, SendyCruz commented on src/Context/AppContext.jsx
> +  const [dataTest, setDataTest] = useState([
¿esta información es la que estarías recibiendo del back para mostrar en el catalogo?

los nombres de las propiedades ej. nombre, deberían estar en inglés

2023-08-04 18:56 UTC, cgarcia-iwa requested changes

2023-08-04 18:56 UTC, cgarcia-iwa commented on src/Components/MedicalPrescriptions/FormMedicalPrescriptions.jsx
> +    console.log(data);
borrar logs

2023-08-04 18:56 UTC, cgarcia-iwa commented on src/Components/MedicalPrescriptions/FormMedicalPrescriptions.jsx
> +    setDataMedicalPrescription(data);
```suggestion
    setMedicalPrescriptionData(data);
```

2023-08-04 18:56 UTC, cgarcia-iwa commented on src/Components/MedicalPrescriptions/FormMedicalPrescriptions.jsx
> +                infoDoctors={dataGetAllDoctors}
```suggestion
                infoDoctors={getAllDoctorsData}
```

2023-08-04 18:56 UTC, cgarcia-iwa commented on src/Components/MedicalPrescriptions/FormMedicalPrescriptions.jsx
> +                infoMedicine={dataGetAllMedicine}
ditto, replicar en casos similares

2023-08-04 18:56 UTC, cgarcia-iwa commented on src/Components/MedicalPrescriptions/PrescriptionTypeahead/TypeaheadPatient.jsx
> +    //   Todo: This sectio is when api is ready
```suggestion
    //   TODO: This sectio is when api is ready
```

2023-08-06 00:13 UTC, Chris-THC commented on src/Components/MedicalPrescriptions/FormMedicalPrescriptions.jsx
> +                infoDoctors={dataGetAllDoctors}
Esa variable le perteneces al CRUD de pacientes y contiene todo el estado de pacientes, por lo que si es cambiada todo el CRUD se quedara son datos que vienen de la API, a lo que se traduce que quedara inutilizable

2023-08-07 16:09 UTC, SendyCruz requested changes

2023-08-07 16:09 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/FormMedicalPrescriptions.jsx
> +          `Preinscripción de ${dataPrescription.patient.name} se ha actualizado exitosamente`
Prescripción

2023-08-07 16:09 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/ModalDelete.jsx
> +                `Se eliminó la preinscripción del paciente ${dataPrescription.patient.name}`
prescripción

2023-08-07 16:09 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/ModalDelete.jsx
> +        <p>¿Está seguro de que desea eliminar esta preinscripción?</p>
prescripción

2023-08-07 16:09 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/PrescriptionTypeahead/TypeaheadDoctor.jsx
> +        <p className="text-danger">El doctor que buscas no se encuentra</p>
```suggestion
        <p className="text-danger">El doctor no existe</p>
```

2023-08-07 16:09 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/PrescriptionTypeahead/TypeaheadPatient.jsx
> +
remover los saltos de líneas sobrantes

2023-08-07 16:09 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/PrescriptionTypeahead/TypeaheadPatient.jsx
> +        <p className="text-danger">El paciente que buscas no se encuentra</p>
```suggestion
        <p className="text-danger">El paciente no existe</p>
```

2023-08-07 16:09 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/TableMedicalPrescriptions.jsx
> +  const [searchByName, setSearchByName] = useState("");
Name de quien?

2023-08-07 16:09 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/TableMedicalPrescriptions.jsx
> +                        placeholder="Buscar por medico..."
```suggestion
                        placeholder="Buscar por médico..."
```

2023-08-07 16:09 UTC, SendyCruz commented on src/Context/Prescription.js
> +export const deletePrescriptionFunction = async (idPrescription) => {
```suggestion
export const deletePrescriptionFunction = async (prescriptionId) => {
```

2023-08-07 16:09 UTC, SendyCruz commented on src/Context/Prescription.js
> +    const urlDelete = `${prescriptions_URL}/${idPrescription}`;
prescriptionId

2023-08-07 16:09 UTC, SendyCruz commented on src/Context/Prescription.js
> +export const updatePrescriptionFunction = async (arrayData, idPrescription) => {
prescriptionId

2023-08-07 16:09 UTC, SendyCruz commented on src/Context/Prescription.js
> +  const urlUpdate = `${prescriptions_URL}/${idPrescription}`;
prescriptionId

2023-08-07 16:34 UTC, SendyCruz requested changes

2023-08-07 16:34 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/FormMedicalPrescriptions.jsx
> +        setTextAlert("Preinscripción medica agregada exitosamente");
```suggestion
        setTextAlert("Prescripción médica agregada exitosamente");
```

2023-08-07 16:34 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/FormMedicalPrescriptions.jsx
> +        setTextAlert("Error al agregar la preinscripción medica");
```suggestion
        setTextAlert("Error al agregar la prescripción médica");
```

2023-08-07 16:34 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/HTTPstatus.js
> +const statusCreated = 201;
HttpStatus

2023-08-07 16:34 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/TableMedicalPrescriptions.jsx
> +                  <th>Medico</th>
```suggestion
                  <th>Médico</th>
```

2023-08-07 17:56 UTC, SendyCruz requested changes

2023-08-07 17:56 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/TableMedicalPrescriptions.jsx
> +                      <label>Medico</label>
```suggestion
                      <label>Medico</label>
```
```suggestion
                      <label>Médico</label>
```

2023-08-07 17:56 UTC, SendyCruz approved these changes

2023-08-08 05:44 UTC, SendyCruz requested changes

2023-08-08 05:44 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/FloatingAlert.jsx
> +  useEffect(() => {
agregar salto de línea

2023-08-08 05:44 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/FloatingAlert.jsx
> +  const AlertMsn = () => {
podrías intentar abstraer los estilos e incliuso sus alertas


algo así

export const FloatingAlert = ({ show, message, onClose }) => {
  const { actionButtonModal } = useContext(GetTheAppContext);

  useEffect(() => {
    if (show) {
      const timer = setTimeout(() => {
        onClose();
      }, 2000);

      return () => clearTimeout(timer);
    }
  }, [show, onClose]);

  const getAlertStyle = () => {
    if (actionButtonModal === "Agregar") {
      return { backgroundColor: "#d4edda" };
    } else if (actionButtonModal === "Editar") {
      return { backgroundColor: "#cce5ff" };
    } else if (actionButtonModal === "Eliminar") {
      return { backgroundColor: "#f8d7da" };
    }
  };

  return (
    <Modal show={show} onHide={onClose} centered>
      <Modal.Body className="text-center" style={getAlertStyle()}>
        <div className={`alert text-muted ${getAlertClass()}`} role="alert">
          {message}
        </div>
      </Modal.Body>
    </Modal>
  );
};

const getAlertClass = () => {
  if (actionButtonModal === "Agregar") {
    return "alert-success";
  } else if (actionButtonModal === "Editar") {
    return "alert-primary";
  } else if (actionButtonModal === "Eliminar") {
    return "alert-danger";
  }
};

2023-08-08 05:44 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/FormMedicalPrescriptions.jsx
> +          `Prescripción de ${dataPrescription.patient.name} se ha actualizado exitosamente`
los mensajes de alerta podrias extraerse aparte:

  const getMessageForAlert = () => {
    if (actionButtonModal === "Agregar") {
      return "Prescripción médica agregada exitosamente";
    } else if (actionButtonModal === "Editar") {
      return `Prescripción de ${dataPrescription.patient.name} se ha actualizado exitosamente`;
    }
    return "";
  };

2023-08-08 06:13 UTC, Chris-THC commented
Listo :)

2023-08-08 16:27 UTC, SendyCruz requested changes

2023-08-08 16:27 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/FormMedicalPrescriptions.jsx
> +  const currentDate = new Date().toISOString().split("T")[0];
agregar un salto de línea antes

2023-08-08 16:27 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/FormMedicalPrescriptions.jsx
> +  const onSubmitClick = async (data) => {
podrías separarlas por acciones:


// Crear

```
  const handleCreatePrescription = async (data) => {
    handleCloseModal();
    const createNewPrescription = await createPrescriptionFunction(data);

    if (createNewPrescription.status === statusCreated) {
      await allPrescriptionsFromApiFunction(setAllPrescriptionsData);
      setTextAlert(getMessageForAlert());
      handleShowFloatAlter();
    } else {
      setTextAlert("Error al agregar la prescripción médica");
      handleShowFloatAlter();
    }
  };
```
  
  
  //Actualizar
  
```
    const handleUpdatePrescription = async (data) => {
    handleCloseModal();
    if (!data.patientId || !data.doctorId) {
      data.patientId = dataPrescription.patientId;
      data.doctorId = dataPrescription.doctorId;
    } else {
      data.patientId = prescriptionPatientId;
      data.doctorId = prescriptionDoctorId;
    }

    const responseUpdatePrescription = await updatePrescriptionFunction(
      data,
      dataPrescription.id
    );

    if (responseUpdatePrescription.status === statusDeleted) {
      setTextAlert(getMessageForAlert());
      await allPrescriptionsFromApiFunction(setAllPrescriptionsData);
      handleShowFloatAlter();
    } else {
      setTextAlert("Error al actualizar la prescripción");
      handleShowFloatAlter();
    }
  };
```
  
  
  // en este llamas a los metodos antes creados
  
```
 const onSubmitClick = async (data) => {
    data.patientId = prescriptionPatientId;
    data.doctorId = prescriptionDoctorId;

    if (actionButtonModal === "Agregar") {
      handleCreatePrescription(data);
    } else if (actionButtonModal === "Editar") {
      handleUpdatePrescription(data);
    }
  };
```

2023-08-08 16:27 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/PrescriptionTypeahead/TypeaheadDoctor.jsx
> +
remover línea

2023-08-08 16:27 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/PrescriptionTypeahead/TypeaheadDoctor.jsx
> +  const valueTypeHeadDoctor = () => {
```suggestion
  const getTypeHeadDoctorValue = () => {
```

2023-08-08 16:27 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/PrescriptionTypeahead/TypeaheadPatient.jsx
> +  const valueTypeHeadPatient = () => {
```suggestion
  const getTypeHeadPatientValue = () => {
```

2023-08-08 16:27 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/PrescriptionTypeahead/TypeaheadPatient.jsx
> +  const handlePatientSelection = (selectedPatients) => {
```suggestion
  const handlePatientSelection = (selectedPatient) => {
```

2023-08-08 18:40 UTC, SendyCruz requested changes

2023-08-08 18:40 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/CrudMedicalPrescriptions.jsx
> +export const CrudMedicalPrescriptions = () => {
```suggestion
export const MedicalPrescriptions = () => {
```

2023-08-08 18:40 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/FloatingAlert.jsx
> +  const AlertMsn = () => {
evitar abreviatura

2023-08-08 19:00 UTC, SendyCruz requested changes

2023-08-08 19:00 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/FloatingAlert.jsx
> +  const getAlertStyle = () => {
revisar los comentarios en la clase FloatingAlert del Pr que tiene abierto mauricio para extraer los estilos a una hoja de estilos

2023-08-08 20:31 UTC, Chris-THC commented on src/Components/MedicalPrescriptions/FloatingAlert.jsx
> +  const getAlertStyle = () => {
el mío ya lo he optimizado en un PR que ya solucione:

  const getAlertClass = () => {
    if (actionButtonModal === "Agregar") {
      return "alert-success";
    } else if (actionButtonModal === "Editar") {
      return "alert-primary";
    } else if (actionButtonModal === "Eliminar") {
      return "alert-danger";
    }
  };

2023-08-08 21:50 UTC, SendyCruz requested changes

2023-08-08 21:50 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/FormMedicalPrescriptions.jsx
> +  const handleCreatePrescription = async (data) => {
```suggestion
  const createPrescription = async (data) => {
```

2023-08-08 21:50 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/FormMedicalPrescriptions.jsx
> +    handleCloseModal();
```suggestion
    closeModal();
```

2023-08-08 21:50 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/FormMedicalPrescriptions.jsx
> +  const handleUpdatePrescription = async (data) => {
```suggestion
  const updatePrescription = async (data) => {
```

2023-08-08 21:50 UTC, SendyCruz commented on src/Components/MedicalPrescriptions/FormMedicalPrescriptions.jsx
> +    const createNewPrescription = await createPrescriptionFunction(data);
```suggestion
    const newPrescription = await createPrescriptionFunction(data);
```

2023-08-08 22:28 UTC, cgarcia-iwa requested changes

2023-08-08 22:28 UTC, cgarcia-iwa commented on src/Components/MedicalPrescriptions/ModalDelete.jsx
> +            console.log(dataPrescription.id);
borrar logs

2023-08-08 22:28 UTC, cgarcia-iwa commented on src/Components/MedicalPrescriptions/PrescriptionTypeahead/TypeaheadDoctor.jsx
> +    if (Object.keys(dataPrescription).length === 0) {
este if y el else regresan lo mismo, refactorizar para evitar esta situacion, igual en los casos parecidos

2023-08-09 00:12 UTC, Chris-THC commented on src/Components/MedicalPrescriptions/FormMedicalPrescriptions.jsx
> +    handleCloseModal();
No puedo cambiar el nombre de esa función, porque es una función de uso general que se reutiliza en cada CRUD, su propósito solo es cerrar el modal.
Si lo cambio tendría que cambiarlo en toda la aplicación en cada sección de de todos los CRUD's en donde se utiliza

2023-08-09 16:30 UTC, SendyCruz approved these changes

2023-08-09 17:10 UTC, cgarcia-iwa requested changes

2023-08-09 17:10 UTC, cgarcia-iwa commented on src/Context/DoctorData.js
>      console.log(response.data);
borrar todos los console.log

2023-08-09 17:52 UTC, cgarcia-iwa approved these changes

2023-08-09 18:43 UTC, merged