Iwaid 14 crud medicos
Chris-THC/IWA-Consultorio-Medico pull request #8
Opened 2023-07-27 17:35 UTC by Mau03gm

Ticket:
[IWAID-14-CRUD-MEDICOS](https://iwaids.atlassian.net/browse/IWAID-14?atlOrigin=eyJpIjoiNzMwODUwN2M1MTc0NDY0ZWFkNjZhMDkyNWI1NDJlNzYiLCJwIjoiaiJ9)

Overview:
Change the table structure and object search, 
create a modal for deletion, update the add and update modals, 
and display dummy objects. 
Modify the form validations to prevent the entry of erroneous data during the data entry process.

How To Test:

Clone the repository
Install the dependencies
In the project directory, you can run:
npm start
This runs the app in the development mode.
Open http://localhost:3000/ to view it in your browser.

Evidence:
![Strat Table](   https://github.com/Mau03gm/CRUDimages/blob/main/CrudImagenes/crudDoctor/Captura%20de%20pantalla%202023-07-27%20111521.png?raw=true
)

![Strat Table](
https://github.com/Mau03gm/CRUDimages/blob/main/CrudImagenes/crudDoctor/Captura%20de%20pantalla%202023-07-27%20111550.png?raw=true
)

![Strat Table](
https://github.com/Mau03gm/CRUDimages/blob/main/CrudImagenes/crudDoctor/Captura%20de%20pantalla%202023-07-27%20111639.png?raw=true    
)

2023-07-27 17:45 UTC, SendyCruz commented
APUNTAR A LA RAMA CORRECTA

2023-07-27 19:46 UTC, SendyCruz requested changes

2023-07-27 19:46 UTC, SendyCruz commented on src/Components/componentsDoctor/DoctorList.jsx
> +  // return <TablaDoctores doctors={Doctors} he />;
remover comentario

2023-07-27 19:46 UTC, SendyCruz commented on src/Components/componentsDoctor/FormDoctor.jsx
> +      El número de teléfono debe tener al menos 10 dígitos
```suggestion
      Debe tener al menos 10 dígitos
```

2023-07-27 19:46 UTC, SendyCruz commented on src/Components/componentsDoctor/FormDoctor.jsx
> +      El número de teléfono debe tener 10 dígitos
esta repetido

2023-07-27 19:46 UTC, SendyCruz commented on src/Components/componentsDoctor/Prueba.jsx
> +import React from 'react'
si no se esta utilizando, remover

2023-07-27 19:46 UTC, SendyCruz commented on src/Components/componentsDoctor/modalDelete.jsx
> +        <Modal.Title>Confirmar Eliminación</Modal.Title>
```suggestion
        <Modal.Title>Confirmar eliminación</Modal.Title>
```

2023-07-27 19:46 UTC, SendyCruz commented on src/Components/componentsDoctor/modalDelete.jsx
> +        <p>¿Estás seguro de que deseas eliminar este usuario?</p>
```suggestion
        <p>¿Está seguro de que desea eliminar este usuario?</p>
```

2023-07-27 19:46 UTC, SendyCruz commented on src/Components/componentsDoctor/table.jsx
> +/*nombre, especialidad, dirección,
remover comentarios

2023-07-27 19:46 UTC, SendyCruz commented on src/Components/componentsDoctor/table.jsx
> +import React, {useState, useContext} from 'react';
src/Components/componentsDoctor/table.jsx

el nombre de la carpeta debería ser Doctor

2023-07-27 19:46 UTC, SendyCruz commented on src/Components/componentsDoctor/table.jsx
> +// export function TablaGenerica({ title, data, headers }) {
remover

2023-07-27 19:48 UTC, SendyCruz requested changes

2023-07-27 19:48 UTC, SendyCruz commented on src/Components/componentsDoctor/modal.jsx
> +        <Modal.Title>{actionButtonModal} Médico</Modal.Title>
en algunos lugares dice médico y en otras en doctor, homogenizar

2023-07-27 19:48 UTC, SendyCruz commented
Actualizar evidencia

2023-07-28 04:12 UTC, Mau03gm commented
I changed the form validations and required data.
<img width="625" alt="Captura de pantalla 2023-07-27 221037" src="https://github.com/Chris-THC/iwaid-ui/assets/139919533/d7659347-5c0f-4b71-9067-d45d67926a23">

2023-07-31 16:41 UTC, SendyCruz requested changes

2023-07-31 16:41 UTC, SendyCruz commented on src/Components/Doctor/FormDoctor.jsx
> +              Ingrese un correo electrónico válido (ejemplo:
remover el ejemplo

2023-07-31 16:41 UTC, SendyCruz commented on src/Components/Doctor/modalDelete.jsx
> +              setTextAlert(`Se eliminó al usuario con id ${idDoctor}`);
Se eliminó al doctor {doctorName}

2023-07-31 16:41 UTC, SendyCruz commented on src/Components/Doctor/table.jsx
> +                  <th>Acción</th>
Acciones

2023-07-31 16:48 UTC, SendyCruz approved these changes

2023-07-31 16:50 UTC, SendyCruz approved these changes

2023-07-31 16:50 UTC, SendyCruz commented on src/Components/Doctor/modalDelete.jsx
> +        <p>¿Está seguro de que desea eliminar este usuario?</p>
```suggestion
        <p>¿Está seguro de que desea eliminar este doctor?</p>
```

2023-07-31 16:55 UTC, SendyCruz approved these changes

2023-07-31 16:55 UTC, SendyCruz commented on src/Components/Doctor/FormDoctor.jsx
> +      setTextAlert("Se editó un doctor");
Doctor actualizado

2023-07-31 16:55 UTC, SendyCruz commented on src/Components/Doctor/FormDoctor.jsx
> +        await updateDoctorFunction(data, idDoctor);
DoctorId

2023-07-31 16:55 UTC, SendyCruz commented on src/Components/Doctor/FormDoctor.jsx
> +              El dato es requerido y debe ser alfanumérico (máximo 100
Dato requerido y alfanúmerico (Max. 100 caracteres)

2023-07-31 16:55 UTC, SendyCruz commented on src/Components/Doctor/FormDoctor.jsx
> +            <span className="text-danger">El dato es requerido</span>
Dato requerido

2023-07-31 16:55 UTC, SendyCruz commented on src/Components/Doctor/FormDoctor.jsx
> +              El dato es requerido y debe ser alfanumérico (máximo 500
Dato requerido y alfanúmerico (Max. 500 caracteres)

2023-07-31 16:55 UTC, SendyCruz commented on src/Components/Doctor/FormDoctor.jsx
> +            placeholder="Número de teléfono"
Número telefónico

2023-07-31 16:55 UTC, SendyCruz commented on src/Components/Doctor/table.jsx
> +                        <GiLargePaintBrush /> Borrar
Limpiar

2023-07-31 16:55 UTC, SendyCruz commented on src/Components/Doctor/table.jsx
> +                        <GiLargePaintBrush /> Borrar
Limpiar

2023-07-31 17:11 UTC, cgarcia-iwa approved these changes

2023-07-31 17:11 UTC, cgarcia-iwa commented on src/Components/Doctor/FormDoctor.jsx
> +        console.error("Error al agregar el médico:", error);
un sistema ya usado por un usuario final no puede depender de console.log
buscar otra forma de mostrar el error en este ticket o crear subtarea

2023-07-31 17:11 UTC, cgarcia-iwa commented on src/Context/DoctorData.js
> +    console.log(response.data);
borrar logs de prueba

2023-07-31 17:11 UTC, cgarcia-iwa commented on src/Context/DoctorData.js
> +    console.log(response.data);
borrar logs de pruebas

2023-07-31 17:11 UTC, cgarcia-iwa commented on src/Components/Doctor/modalDelete.jsx
> +              await deleteDoctorFunction(idDoctor);
renombrar variable 
```suggestion
              await deleteDoctorFunction(doctorId);
```

2023-07-31 18:22 UTC, SendyCruz commented
Vista de filtrado:
Subir el botón de filtrado al nivel de los inputs
Cambiar botón de limpiar por un icono y agregar un tooltip con la leyenda Limpiar filtros

Catalogo:
Acción  - Acciones
Botones solo dejar icono y agregar tooltip con el nombre de la acción


Modal:
- Agregar un espacio considerable entre las entradas
- Especialización - Especialidad
- número con acento

2023-07-31 20:21 UTC, merged