Iwaid 11 crud medicamentos
Chris-THC/IWA-Consultorio-Medico pull request #9
Opened 2023-07-27 17:42 UTC by Mau03gm

Ticket:
[IWAID-11-CRUD-MEDICAMENTOS](
https://iwaids.atlassian.net/browse/IWAID-11?atlOrigin=eyJpIjoiZjQ4NTM0NzJkZDQxNDg0ZWFhZjcyYjg0YzBiNzNkOGQiLCJwIjoiaiJ9
)

Overview:
Change the table structure and object search, 
create a modal for deletion, update the add and update modals, 
and display dummy objects. 
Modify the form validations to prevent the entry of erroneous data during the data entry process.

How To Test:

Clone the repository
Install the dependencies
In the project directory, you can run:
npm start
This runs the app in the development mode.
Open http://localhost:3000/ to view it in your browser.

Evidence:
![Strat Table](   
https://github.com/Mau03gm/CRUDimages/blob/main/CrudImagenes/crudMedicamentos/Captura%20de%20pantalla%202023-07-27%20111231.png?raw=true
)

![Strat Table](
https://github.com/Mau03gm/CRUDimages/blob/main/CrudImagenes/crudMedicamentos/Captura%20de%20pantalla%202023-07-27%20111311.png?raw=true
)

![Strat Table](
https://github.com/Mau03gm/CRUDimages/blob/main/CrudImagenes/crudMedicamentos/Captura%20de%20pantalla%202023-07-27%20111401.png?raw=true
)

![Strat Table](
https://github.com/Mau03gm/CRUDimages/blob/main/CrudImagenes/crudMedicamentos/Captura%20de%20pantalla%202023-07-27%20111440.png?raw=true
)

2023-08-01 00:29 UTC, SendyCruz requested changes

2023-08-01 00:29 UTC, SendyCruz commented on src/Components/Medicine/FormMedicine.jsx
> +          <label>Nombre de la medicina</label>
```suggestion
          <label>Nombre del medicamento</label>
```

2023-08-01 00:29 UTC, SendyCruz commented on src/Components/Medicine/FormMedicine.jsx
> +          <label>Nombre de la medicina</label>
```suggestion
          <label>Nombre del medicamento</label>
```

2023-08-01 00:29 UTC, SendyCruz commented on src/Components/Medicine/FormMedicine.jsx
> +            placeholder="Nombre de la medicina"
```suggestion
            placeholder="Nombre del medicamento"
```

2023-08-01 00:29 UTC, SendyCruz commented on src/Components/Medicine/FormMedicine.jsx
> +            <span className="text-danger">El dato es requerido</span>
```suggestion
            <span className="text-danger">Dato requerido</span>
```

2023-08-01 00:29 UTC, SendyCruz commented on src/Components/Medicine/FormMedicine.jsx
> +      min: 0, // Puedes ajustar el mínimo de la dosis según tus necesidades
remover comentario

2023-08-01 00:29 UTC, SendyCruz commented on src/Components/Medicine/FormMedicine.jsx
> +      min: 0, // Puedes ajustar el mínimo de la dosis según tus necesidades
es correcto que el minimo sea 0? por que?

2023-08-01 00:29 UTC, SendyCruz commented on src/Components/Medicine/FormMedicine.jsx
> +                defaultValue={isGetData.presentation} // Aquí se asigna el valor al select
eliminar comentario

2023-08-01 00:29 UTC, SendyCruz commented on src/Components/Medicine/FormMedicine.jsx
> +                <option value="Sólidos">Sólidos</option>
Estos datos así estan definidos en el back? en plural?

2023-08-01 00:29 UTC, SendyCruz commented on src/Components/Medicine/FormMedicine.jsx
> +    <span className="text-danger">El dato es requerido</span>
```suggestion
    <span className="text-danger">Dato requerido</span>
```

2023-08-01 00:29 UTC, SendyCruz commented on src/Components/Medicine/FormMedicine.jsx
> +            <span className="text-danger">El dato es requerido</span>
ditto

2023-08-01 00:33 UTC, SendyCruz requested changes

2023-08-01 00:33 UTC, SendyCruz commented on src/Components/Medicine/table.jsx
> +  // const[id, setid] = useState(null);
eliminar comentarios

2023-08-01 00:33 UTC, SendyCruz commented on src/Components/Medicine/table.jsx
> +    const nombreMatches = item.name
cambiar nombre,  usar inglés

2023-08-01 00:33 UTC, SendyCruz commented on src/Components/Medicine/table.jsx
> +    const dosisMatches = item.dosis.includes(searchDosis);
ditto

2023-08-01 00:33 UTC, SendyCruz commented on src/Components/Medicine/table.jsx
> +    setSearchDosis("");
```suggestion
    setSearchDoses("");
```

2023-08-01 00:33 UTC, SendyCruz commented on src/Components/Medicine/table.jsx
> +                          setSearchName(e.target.value);
usar inglés, aplica para los de abajo tambien

2023-08-01 19:37 UTC, cgarcia-iwa requested changes

2023-08-01 19:37 UTC, cgarcia-iwa commented on src/Components/Medicine/table.jsx
> +                  <th> Cantidad</th>
```suggestion
                  <th>Cantidad</th>
```

2023-08-01 19:37 UTC, cgarcia-iwa commented on src/Context/MedicineData.js
> +export const createMedicineFunction = async (arrayData) => {
estos cambios por que estan en este PR?

2023-08-01 19:37 UTC, cgarcia-iwa commented on src/Context/MedicineData.js
> +  console.log(arrayData);
borrar los logs

2023-08-01 19:37 UTC, cgarcia-iwa commented on src/Context/MedicineData.js
> +export const getAllMedicineDataFunction = async (setGetAllMedicine) => {
cambiar el setGetallMedicine por un nombre mas coherente

2023-08-01 23:02 UTC, SendyCruz requested changes

2023-08-01 23:02 UTC, SendyCruz commented on src/Components/Medicine/FormMedicine.jsx
> +                      <option value="Liquida">Liquida</option>
```suggestion
                      <option value="Liquida">Líquida</option>
```

2023-08-01 23:02 UTC, SendyCruz commented on src/Components/Medicine/FormMedicine.jsx
> +          <span className="text-danger">*Dato requerido</span>
```suggestion
          <span className="text-danger">Dato requerido</span>
```

2023-08-01 23:02 UTC, SendyCruz commented on src/Components/Medicine/FormMedicine.jsx
> +          <span className="text-danger">Límite superado</span>
cual es el limite? Cambiar texto

2023-08-01 23:02 UTC, SendyCruz commented on src/Components/Medicine/FormMedicine.jsx
> +      <label>Cantidad</label>
sí es requerido, debeía llevar un * rojo a la derecha, revisar cambios hechos en CRUD medicos

2023-08-01 23:02 UTC, SendyCruz commented on src/Components/Medicine/FormMedicine.jsx
> +        <span className="text-danger">*Dato requerido</span>
```suggestion
        <span className="text-danger">Dato requerido</span>
```

2023-08-01 23:02 UTC, SendyCruz commented on src/Components/Medicine/FormMedicine.jsx
> +        <label>Descripción
si es requerido, debeía llevar un * rojo a la derecha, revisar cambios hechos en CRUD medicos

2023-08-01 23:02 UTC, SendyCruz commented on src/Components/Medicine/FormMedicine.jsx
> +          <span className="text-danger">*Solo caracteres alfanuméricos</span>
```suggestion
          <span className="text-danger">Solo caracteres alfanuméricos</span>
```

2023-08-01 23:02 UTC, SendyCruz commented on src/Components/Medicine/FormMedicine.jsx
> +          <span className="text-danger">*Máximo 5 caracteres</span>
```suggestion
          <span className="text-danger">Máximo 5 caracteres</span>
```

2023-08-01 23:02 UTC, SendyCruz commented on src/Components/Medicine/FormMedicine.jsx
> +          <span className="text-danger">*Dato requerido</span>
```suggestion
          <span className="text-danger">Dato requerido</span>
```

2023-08-01 23:02 UTC, SendyCruz commented on src/Components/Medicine/MedicineList.jsx
> +   //return <TablaGeneric  title='MEDICAMENTOS' data={dataTestMedicine}  />
delete

2023-08-01 23:02 UTC, SendyCruz commented on src/Components/Medicine/modalDelete.jsx
> +              console.error("Error al agregar el médico:", error);
```suggestion
              console.error("Error al eliminar médico:", error);
```

2023-08-01 23:02 UTC, SendyCruz commented on src/Components/Medicine/table.jsx
> +          id="iconoClear"
es necesario id?

2023-08-02 16:01 UTC, SendyCruz commented
Actualizar rama con develop y actualizar SS de la evidencia

2023-08-02 16:09 UTC, SendyCruz requested changes

2023-08-02 16:09 UTC, SendyCruz commented on src/Components/Medicine/FormMedicine.jsx
> +          <span className="text-danger">El dato es requerido</span>
```suggestion
          <span className="text-danger">Dato requerido</span>
```

2023-08-02 16:09 UTC, SendyCruz commented on src/Components/Medicine/FormMedicine.jsx
> +            Solo caracteres alfanuméricos y espacios
```suggestion
            Solo caracteres alfanuméricos
```

2023-08-02 16:09 UTC, SendyCruz commented on src/Components/Medicine/table.jsx
> +                        <div id="idTextPatient" className="d-inline">
patient?

2023-08-02 16:09 UTC, SendyCruz commented on src/Components/Medicine/table.jsx
> +                            id="btnDeletePatient"
```suggestion
                            id="btnDeleteMedicine"
```

2023-08-02 16:09 UTC, SendyCruz commented on src/Css/CssTable.css
> +  #inputSearchPatient {
si los estilos son  dedicados por cada componente entonces los de este se deberian llamar con respecto a medicina y no a paciente

2023-08-02 19:04 UTC, cgarcia-iwa requested changes
Quitar todos los patiens de los archivos de medicina

2023-08-02 19:04 UTC, cgarcia-iwa commented on src/Components/Medicine/FormMedicine.jsx
> +        console.error("Error al agregar el medicamento:", error);
seria posible agregar los errores con el setTextAlert con alguna variacion?

2023-08-02 19:04 UTC, cgarcia-iwa commented on src/Components/Medicine/table.jsx
> +        {allPackaging.map((packaging, index) => (
en back se maneja un nombre distinto, homologar

2023-08-02 21:17 UTC, SendyCruz approved these changes

2023-08-02 22:21 UTC, cgarcia-iwa requested changes

2023-08-02 22:21 UTC, cgarcia-iwa commented on src/Components/Medicine/FormMedicine.jsx
> +      if (responseCreateMedicine.status === 201) {
puedes guardar en algun tipo de enum los status para evitar usar los numeros directamente en las comparativas

2023-08-02 22:21 UTC, cgarcia-iwa commented on src/Components/Medicine/table.jsx
> +    const packagingMatches = searchPackaging
packaging es correcto? en caso de no serlo renombrar todos los casos pendientes

2023-08-02 22:21 UTC, cgarcia-iwa commented on src/Context/MedicineData.js
> +    console.log(arrayData);
borrar logs

2023-08-02 22:21 UTC, cgarcia-iwa commented on src/Context/MedicineData.js
> +    console.log(response);
ditto

2023-08-02 22:27 UTC, SendyCruz commented on src/Components/Medicine/FormMedicine.jsx
> +      if (responseCreateMedicine.status === 201) {
tambien podría ser una constante, actualizar en los archivos necesarios

2023-08-02 22:55 UTC, cgarcia-iwa requested changes

2023-08-02 22:55 UTC, cgarcia-iwa commented on src/Components/Medicine/modalDelete.jsx
> +              idMedicine
es correcto el valor o es medicineId?

2023-08-02 22:55 UTC, cgarcia-iwa commented on src/Components/Medicine/BackendVariables.js
> +const statusCreated = 201;
renombrar nombre a archivo para hacer match con los HTTP status

2023-08-02 22:55 UTC, cgarcia-iwa commented on src/Components/Medicine/table.jsx
> +                        {allPackaging.map((packaging, index) => (
buscar en los archivos del PR todos los packaging y renombrar en caso de ser necesario

2023-08-02 23:05 UTC, cgarcia-iwa approved these changes

2023-08-02 23:06 UTC, merged